In [3]:
import numpy as np  
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a)
print(b)
print("\n vector addition")
print(a+b)
print("\n vector substraction")
print(a-b)
print("\n vector multiplication")
print(a*b)
print("\n vector division")
print(a/b)
print("\n vector dot product")
print(a.dot(b))
print("\n scalar multiplication")
sclr=5
print("scalar value=",sclr)

Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

 vector addition
[12 24 35 48 60]

 vector substraction
[ 8 16 25 32 40]

 vector multiplication
[ 20  80 150 320 500]

 vector division
[5. 5. 6. 5. 5.]

 vector dot product
1070

 scalar multiplication
scalar value= 5


In [4]:
#numpy.vectorize method
def my_func(x,y):
    #return x-y if x>y,otherwise return x+y
    if x>y:
        return x-y
    else:
        return x+y
print("\n\n Numpy.vectorize method")
print("(Return x-y if x>y,otherwise return x+y)")
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("array1:",arr1)
print("array2:",arr2)
print("reuslt:",vec_func(arr1,arr2))



 Numpy.vectorize method
(Return x-y if x>y,otherwise return x+y)
array1: [10, 4, 20]
array2: [2, 3, 30]
reuslt: [ 8  1 50]
