In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 6 4]
(array([3, 6]),)


In [2]:
#indexes where the values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [4]:
#string the array
arr=np.array([3,2,0,1])
print("\nOriginal array:",arr)
print("\nSorted array:",arr)
arr=np.array([[3,2,4],[5,0,1]])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))


Original array: [3 2 0 1]

Sorted array: [3 2 0 1]

Original array: [[3 2 4]
 [5 0 1]]

Sorted array: [[2 3 4]
 [0 1 5]]


In [6]:
#Filter
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition-42:",filter_arr)
print("\nNewarray:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]

Original array: [41 42 43 44]

Filter array:condition-42: [False False  True  True]

Newarray: [43 44]
